CREATE DATABASE IF NOT EXISTS tnoDB;

use tnoDB;

create table Estudiante(
    ID_ESTUDIANTE INT NOT NULL auto_increment,
    DNI INT,
    NOMBRES VARCHAR(250),
    APELLIDOS VARCHAR(250),
    EDAD INT,
    FECHA_NACIMIENTO DATETIME,
    CELULAR INT,
    DIRECCION VARCHAR(259),
    ESTADO INT,
    FECHA_REG DATETIME,
    FECHA_ACT DATETIME,
    primary key(ID_ESTUDIANTE)
);

create table Docente(
    ID_DOCENTE INT NOT NULL auto_increment,
    DNI INT,
    NOMBRES VARCHAR(250),
    APELLIDOS VARCHAR(250),
    EDAD INT,
    FECHA_NACIMIENTO DATETIME,
    CELULAR INT,
    DIRECCION VARCHAR(259),
    ESTADO INT,
    FECHA_REG DATETIME,
    FECHA_ACT DATETIME,
    primary key(ID_DOCENTE)
);

create table Grupo(
    ID_GRUPO INT NOT NULL auto_increment,
    DESCRIPCION VARCHAR(250),
    HORARIO VARCHAR(250),
    ESTADO INT,
    FK_ID_DOCENTE INT,
    FECHA_REG DATETIME,
    FECHA_ACT DATETIME,
    primary key(ID_GRUPO),
    FOREIGN KEY (FK_ID_DOCENTE) REFERENCES Docente(ID_DOCENTE)
);

create table Apoderado(
    ID_APODERADO INT NOT NULL auto_increment,
    DNI INT,
    NOMBRES VARCHAR(250),
    APELLIDOS VARCHAR(250),
    EDAD INT,
    FECHA_NACIMIENTO DATETIME,
    CELULAR INT,
    DIRECCION VARCHAR(250),
    PARENTESCO VARCHAR(250),
    ESTADO INT,
    FK_ID_ESTUDIANTE INT,
    FECHA_REG DATETIME,
    FECHA_ACT DATETIME,
    primary key(ID_APODERADO),
    FOREIGN KEY (FK_ID_ESTUDIANTE) REFERENCES Estudiante(ID_ESTUDIANTE)
);

create table Matricula(
    ID_MATRICULA INT NOT NULL auto_increment,
    FK_ID_ESTUDIANTE INT NOT NULL,
    FK_ID_APODERADO INT NOT NULL,
    FK_ID_GRUPO INT NOT NULL,
    GRADO VARCHAR(50),
    NIVEL VARCHAR(200),
    CICLO VARCHAR(200),
    ANIO INT,
    ESTADO INT,
    FECHA_REG DATETIME,
    FECHA_ACT DATETIME,
    primary key(ID_MATRICULA),
    FOREIGN KEY (FK_ID_ESTUDIANTE) REFERENCES Estudiante(ID_ESTUDIANTE),
    FOREIGN KEY (FK_ID_APODERADO) REFERENCES Apoderado(ID_APODERADO),
    FOREIGN KEY (FK_ID_GRUPO) REFERENCES Grupo(ID_GRUPO)
);